### ISSUE TITLE
ESLint setup

### ISSUE THREAD

**Issue by sumitshetye2** [cse110-sp23-group24/cse110-sp23-group24-Final-Project#1]
I have set up ESLint on this repository with that will check any JavaScript files will write abide by the following rules:
indent: 2 spaces
quotes: single quotes(for strings, etc)
semicolon: always
warn for unused variables

Will change soon so that indenting is done via tab spacing and using double quotes instead of single quotes

**Comment by NickHo2048** [comment]
ESLint setup was finalized
