### ISSUE TITLE
CI/CD Pipeline Markdown File

### ISSUE THREAD

**Issue by Maanasa64** [cse110-sp23-group24/cse110-sp23-group24-Final-Project#2]
CI/CD pipeline phase 1 should be a vetting phase were you explore the following ideas

linting and code style enforcement (may happen in pipeline and/or in editor)
code quality via tool  (ex. Codeclimate, Codacy, etc.)
code quality via human review (ex. Pull Requests)
unit tests via automation (ex. Jest, Tape, Ava, Cypress, Mocha/Chai, etc.)*
documentation generation via automation (ex. JSDocs)

**Comment by NickHo2048** [comment]
Maanasa created the ci/cd pipeline file
