### ISSUE TITLE
Result Page CSS

### ISSUE THREAD

**Issue by kgugnani** [cse110-sp23-group24/cse110-sp23-group24-Final-Project#49]
Make result page look like the rest of the app.

**Comment by kgugnani** [comment]
Worked on the following tasks:

 Result page CSS including background, text font
 Displayed images on result page
 Added go back button with hover effect, navigates to home page
 Parsed through names of cards and used replace(), split(), and join() to make names look a lot nicer

**Comment by NickHo2048** [comment]
results page is completed
